#!/bin/sh
set -eu

mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${LINEABAR_DB_USER}'@'%' IDENTIFIED BY '${LINEABAR_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${LINEABAR_MIGRATIONS_USER}'@'%' IDENTIFIED BY '${LINEABAR_MIGRATIONS_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MARIADB_DATABASE}\`.* TO '${LINEABAR_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES ON \`${MARIADB_DATABASE}\`.* TO '${LINEABAR_MIGRATIONS_USER}'@'%';
FLUSH PRIVILEGES;
SQL
